apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

# kubectl get persistentvolumeclaim
# kubectl apply -f local-pvc.yaml
# kubectl delete persistentvolumeclaim mssql-claim